name: CI build & push images to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Back ----
      - name: Build & push back
        working-directory: ./gestion-scolaire-back
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gestion-back:latest \
                       -t ghcr.io/${{ github.repository_owner }}/gestion-back:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/gestion-back:latest
          docker push ghcr.io/${{ github.repository_owner }}/gestion-back:${{ github.sha }}

      # ---- Front admin (Angular) ----
      - name: Build & push front-admin
        working-directory: ./gestion-scolaire-front/gestion-scolaire
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gestion-front:latest \
                       -t ghcr.io/${{ github.repository_owner }}/gestion-front:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/gestion-front:latest
          docker push ghcr.io/${{ github.repository_owner }}/gestion-front:${{ github.sha }}

      # ---- Front Ã©tudiant ----
      - name: Build & push espace-etudiant
        working-directory: ./espace-etudiant-app/espace-etudiant
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/espace-etudiant:latest \
                       -t ghcr.io/${{ github.repository_owner }}/espace-etudiant:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/espace-etudiant:latest
          docker push ghcr.io/${{ github.repository_owner }}/espace-etudiant:${{ github.sha }}
